### ISSUE TITLE
can't build on ubuntu 16.04 when source update

### ISSUE THREAD

**Issue by 2pay** [dime-coin/dimecoin#5]
Beforce update source i am build success but when update to qt5 it show error:

Command:

```
cd dimecoin/src/leveldb/
sudo chmod 775 build_detect_platform
sudo make libleveldb.a libmemenv.a
cd ..
sudo make -f makefile.unix USE_UPNP=1 USE_QRCODE=1 USE_UPNP=1
```

Show error:

```
/bin/sh ../share/genbuild.sh obj/build.h
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_                                                                   THREADSAFE -D_FILE_OFFSET_BITS=64 -I/home/vno/compil/dimecoin/src -I/home/vno/compil/dimecoin/src/obj                                                                    -DUSE_UPNP=1 -DUSE_IPV6=1 -I/home/vno/compil/dimecoin/src/leveldb/include -I/home/vno/compil/dimecoi                                                                   n/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector                                                                    -D_FORTIFY_SOURCE=2  -MMD -MF obj/db.d -o obj/db.o db.cpp
In file included from netbase.h:10:0,
                 from util.h:31,
                 from bignum.h:12,
                 from main.h:8,
                 from db.h:8,
                 from db.cpp:6:
wallet.h: In member function ‘unsigned int CAccountingEntry::GetSerializeSize(int, int) const’:
wallet.h:831:69: error: no matching function for call to ‘CDataStream::insert(CDataStream::iterator,                                                                    std::vector<char>::const_iterator, std::vector<char>::const_iterator)’
                 ss.insert(ss.end(), _ssExtra.begin(), _ssExtra.end());
                                                                     ^
serialize.h:67:10: note: in definition of macro ‘IMPLEMENT_SERIALIZE’
         {statements}                            \
          ^
In file included from netbase.h:10:0,
                 from util.h:31,
                 from bignum.h:12,
                 from main.h:8,
                 from db.h:8,
                 from db.cpp:6:
serialize.h:895:14: note: candidate: CDataStream::iterator CDataStream::insert(CDataStream::iterator,                                                                    const char&)
     iterator insert(iterator it, const char& x=char()) { return vch.insert(it, x); }
              ^
serialize.h:895:14: note:   candidate expects 2 arguments, 3 provided
serialize.h:896:10: note: candidate: void CDataStream::insert(CDataStream::iterator, CDataStream::siz                                                                   e_type, const char&)
     void insert(iterator it, size_type n, const char& x) { vch.insert(it, n, x); }
          ^
serialize.h:896:10: note:   no known conversion for argument 2 from ‘std::vector<char>::const_iterato                                                                   r {aka __gnu_cxx::__normal_iterator<const char*, std::vector<char> >}’ to ‘CDataStream::size_type {ak                                                                   a long unsigned int}’
serialize.h:898:10: note: candidate: void CDataStream::insert(CDataStream::iterator, CDataStream::con                                                                   st_iterator, CDataStream::const_iterator)
     void insert(iterator it, const_iterator first, const_iterator last)
          ^
serialize.h:898:10: note:   no known conversion for argument 2 from ‘std::vector<char>::const_iterato                                                                   r {aka __gnu_cxx::__normal_iterator<const char*, std::vector<char> >}’ to ‘CDataStream::const_iterato                                                                   r {aka __gnu_cxx::__normal_iterator<const char*, std::vector<char, zero_after_free_allocator<char> >                                                                    >}’
serialize.h:925:10: note: candidate: void CDataStream::insert(CDataStream::iterator, const char*, con                                                                   st char*)
     void insert(iterator it, const char* first, const char* last)
          ^
serialize.h:925:10: note:   no known conversion for argument 2 from ‘std::vector<char>::const_iterato                                                                   r {aka __gnu_cxx::__normal_iterator<const char*, std::vector<char> >}’ to ‘const char*’
In file included from netbase.h:10:0,
                 from util.h:31,
                 from bignum.h:12,
                 from main.h:8,
                 from db.h:8,
                 from db.cpp:6:
wallet.h: In member function ‘void CAccountingEntry::Serialize(Stream&, int, int) const’:
wallet.h:831:69: error: no matching function for call to ‘CDataStream::insert(CDataStream::iterator&,                                                                    std::vector<char>::const_iterator&, std::vector<char>::const_iterator&)’
                 ss.insert(ss.end(), _ssExtra.begin(), _ssExtra.end());
                                                                     ^
serialize.h:79:10: note: in definition of macro ‘IMPLEMENT_SERIALIZE’
         {statements}                            \
          ^
In file included from netbase.h:10:0,
                 from util.h:31,
                 from bignum.h:12,
                 from main.h:8,
                 from db.h:8,
                 from db.cpp:6:
serialize.h:895:14: note: candidate: CDataStream::iterator CDataStream::insert(CDataStream::iterator,                                                                    const char&)
     iterator insert(iterator it, const char& x=char()) { return vch.insert(it, x); }
              ^
serialize.h:895:14: note:   candidate expects 2 arguments, 3 provided
serialize.h:896:10: note: candidate: void CDataStream::insert(CDataStream::iterator, CDataStream::siz                                                                   e_type, const char&)
     void insert(iterator it, size_type n, const char& x) { vch.insert(it, n, x); }
          ^
serialize.h:896:10: note:   no known conversion for argument 2 from ‘std::vector<char>::const_iterato                                                                   r {aka __gnu_cxx::__normal_iterator<const char*, std::vector<char> >}’ to ‘CDataStream::size_type {ak                                                                   a long unsigned int}’
serialize.h:898:10: note: candidate: void CDataStream::insert(CDataStream::iterator, CDataStream::con                                                                   st_iterator, CDataStream::const_iterator)
     void insert(iterator it, const_iterator first, const_iterator last)
          ^
serialize.h:898:10: note:   no known conversion for argument 2 from ‘std::vector<char>::const_iterato                                                                   r {aka __gnu_cxx::__normal_iterator<const char*, std::vector<char> >}’ to ‘CDataStream::const_iterato                                                                   r {aka __gnu_cxx::__normal_iterator<const char*, std::vector<char, zero_after_free_allocator<char> >                                                                    >}’
serialize.h:925:10: note: candidate: void CDataStream::insert(CDataStream::iterator, const char*, con                                                                   st char*)
     void insert(iterator it, const char* first, const char* last)
          ^
serialize.h:925:10: note:   no known conversion for argument 2 from ‘std::vector<char>::const_iterato                                                                   r {aka __gnu_cxx::__normal_iterator<const char*, std::vector<char> >}’ to ‘const char*’
In file included from netbase.h:10:0,
                 from util.h:31,
                 from bignum.h:12,
                 from main.h:8,
                 from db.h:8,
                 from db.cpp:6:
wallet.h: In member function ‘void CAccountingEntry::Unserialize(Stream&, int, int)’:
wallet.h:831:69: error: no matching function for call to ‘CDataStream::insert(CDataStream::iterator&,                                                                    std::vector<char>::iterator&, std::vector<char>::iterator&)’
                 ss.insert(ss.end(), _ssExtra.begin(), _ssExtra.end());
                                                                     ^
serialize.h:90:10: note: in definition of macro ‘IMPLEMENT_SERIALIZE’
         {statements}                            \
          ^
In file included from netbase.h:10:0,
                 from util.h:31,
                 from bignum.h:12,
                 from main.h:8,
                 from db.h:8,
                 from db.cpp:6:
serialize.h:895:14: note: candidate: CDataStream::iterator CDataStream::insert(CDataStream::iterator,                                                                    const char&)
     iterator insert(iterator it, const char& x=char()) { return vch.insert(it, x); }
              ^
serialize.h:895:14: note:   candidate expects 2 arguments, 3 provided
serialize.h:896:10: note: candidate: void CDataStream::insert(CDataStream::iterator, CDataStream::siz                                                                   e_type, const char&)
     void insert(iterator it, size_type n, const char& x) { vch.insert(it, n, x); }
          ^
serialize.h:896:10: note:   no known conversion for argument 2 from ‘std::vector<char>::iterator {aka                                                                    __gnu_cxx::__normal_iterator<char*, std::vector<char> >}’ to ‘CDataStream::size_type {aka long unsig                                                                   ned int}’
serialize.h:898:10: note: candidate: void CDataStream::insert(CDataStream::iterator, CDataStream::con                                                                   st_iterator, CDataStream::const_iterator)
     void insert(iterator it, const_iterator first, const_iterator last)
          ^
serialize.h:898:10: note:   no known conversion for argument 2 from ‘std::vector<char>::iterator {aka                                                                    __gnu_cxx::__normal_iterator<char*, std::vector<char> >}’ to ‘CDataStream::const_iterator {aka __gnu                                                                   _cxx::__normal_iterator<const char*, std::vector<char, zero_after_free_allocator<char> > >}’
serialize.h:925:10: note: candidate: void CDataStream::insert(CDataStream::iterator, const char*, con                                                                   st char*)
     void insert(iterator it, const char* first, const char* last)
          ^
serialize.h:925:10: note:   no known conversion for argument 2 from ‘std::vector<char>::iterator {aka                                                                    __gnu_cxx::__normal_iterator<char*, std::vector<char> >}’ to ‘const char*’
makefile.unix:181: recipe for target 'obj/db.o' failed
make: *** [obj/db.o] Error 1
```

i am build on Ubuntu 16.04
